### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by L1Q** [outfrost/shadowclad#29]
Without a license a project is basically private and closed source, but code "happens to be available".
https://choosealicense.com/no-permission/
https://opensource.stackexchange.com/a/1721

**Comment by outfrost** [comment]
That is currently intentional, as I haven't chosen an appropriate license yet. I do however intend to do so, so this goes on the to do list :)

**Comment by outfrost** [comment]
I'm thinking of licensing the project under [MPL-2.0](https://choosealicense.com/licenses/mpl-2.0/).
